// Menu items from Stanford Faculty Club
var menu = [
    {title: "Papaya Salad",
     description: "arugula, green papaya slaw, peppers, carrots, cilantro and mint in a Vinaigrette dressing",
     price: 14,
     category: "Salad",
     dietaryInformation: ["Vegetarian", "Gluten-Free"]},
    {title: "Grilled Peach & Burrata Salad",
     description: "arugula, prosciutto and basil, drizzled with balsamic reduction",
     price: 16,
     category: "Salad",
     dietaryInformation: ["Vegetarian", "Gluten-Free"]},
    {title: "Chicken Cobb Salad",
     description: "field greens, grape tomatoes, avocado, bacon, gorgonzola cheese, hard boiled eggs and blue cheese dressing ",
     price: 16,
     category: "Salad",
     dietaryInformation: ["Gluten-Free"]},
    {title: "Tuna Salad Sandwich",
     description: "mayonnaise, lettuce and tomato on toasted 9-grain bread with a seasonal fruit cup",
     price: 13,
     category: "Sandwich"},
    {title: "Stanford Chicken Club",
     description: "sourdough bread, pesto mayonnaise, avocado, lettuce, tomato and bacon served with a tossed salad",
     price: 16,
     category: "Sandwich"},
    {title: "Beyond Burger",
     description: "plant-based, 20g protein, brioche bun with lettuce, tomato, red onion and French fries",
     price: 17,
     category: "Burger",
     dietaryInformation: ["Vegetarian"]},
     {title: "Fire Grilled Cheese Burger",
     description: "brioche bun with cheddar cheese, lettuce, tomato, red onion, garlic aioli and French fries",
     price: 18,
     category: "Burger"},
    {title: "Wild Mushroom and Caramelized Onion Ravioli ",
     description: "rustic plum tomato, oregano and thyme ragout",
     price: 15,
     category: "Entree",
     dietaryInformation: ["Vegetarian"]},
    {title: "Blackened Salmon Filet",
     description: "bulgur wheat salad with cucumbers, chick peas, peppers, red onion, dill and parsley",
     price: 18,
     category: "Entree"},
    {title: "Seasonal Sorbet",
     description: "ask waiter for current flavors",
     price: 5,
     category: "Dessert",
     dietaryInformation: ["Vegetarian", "Gluten-Free"]},
    {title: "Cookies",
     description: "Two Cookies",
     price: 3,
     category: "Dessert",
     dietaryInformation: ["Vegetarian"]}
]